### ISSUE TITLE
Question: how to use data-store-js from Stencil / Cornerstone?

### ISSUE THREAD

**Issue by jbruni** [bigcommerce/data-store-js#12]
I've just found this repository.

But I do not see any announcement or documentation...

I'm curious about how/where does this fit into a bigger picture. I've mentioned Cornerstone... but this looks like a piece of some "next-generation-theme" in the making...

**Comment by jbruni** [comment]
@davidchin @bookernath - Can you please shed some light?

**Comment by icatalina** [comment]
Hi @jbruni!

This repository is a dependency of https://github.com/bigcommerce/checkout-sdk-js 

**It has nothing to do with cornerstone or stencil.**

You can have a read at the https://github.com/bigcommerce/data-store-js/blob/master/README.md file in this repo to understand what it does.

Kind Regards,
Ignacio Catalina

**Comment by jbruni** [comment]
Thanks, @icatalina

I'm closing this issue because the question has been answered.
